# Generated by Django 4.2.2 on 2023-07-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerproduct',
            name='resource_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerproduct',
            name='unit_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerproduct',
            name='waste_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerresource',
            name='center_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerresource',
            name='import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerresource',
            name='product_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerresource',
            name='resource_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerresource',
            name='transport_emission_factor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='center_resource_transport', to='database.emissionfactor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centerresource',
            name='unit_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerresource',
            name='use_emission_factor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='center_resource_use', to='database.emissionfactor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centerresource',
            name='waste_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerwaste',
            name='center_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerwaste',
            name='emission_factor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='center_wastes', to='database.emissionfactor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centerwaste',
            name='import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerwaste',
            name='product_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerwaste',
            name='resource_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerwaste',
            name='unit_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centerwaste',
            name='waste_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
