# Generated by Django 4.2.2 on 2023-07-25 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('import_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_german', models.CharField(max_length=255, null=True)),
                ('emission_factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.emissionfactor')),
            ],
        ),
        migrations.AddField(
            model_name='productgroup',
            name='emission_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.emissionfactor'),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('import_id', models.IntegerField(primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=255)),
                ('weight', models.FloatField(null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.productcatalogue')),
            ],
        ),
    ]
