# Generated by Django 4.2.2 on 2023-07-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_centerproduct_resource_import_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerwaste',
            name='emission_factor_import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
