# Generated by Django 4.2.2 on 2023-07-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_centerproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='import_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
