# Generated by Django 4.2.2 on 2023-07-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_centerresource_transport_emission_factor_import_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerresource',
            name='name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
