# Generated by Django 4.2.2 on 2023-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_emissionfactor_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerproduct',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
