# Generated by Django 4.2.2 on 2023-07-10 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_centerresource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransportemission',
            name='transport_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_transport_emissions', to='database.transportstep'),
        ),
    ]
