# Generated by Django 4.2.2 on 2023-07-10 23:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_producttransportemission_transport_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_evaluators', to='database.center')),
                ('electricity_used_emissions', models.ManyToManyField(related_name='emission_evaluators', to='database.electricityusedemission')),
                ('product_emissions', models.ManyToManyField(related_name='emission_evaluators', to='database.productemission')),
                ('product_transport_emissions', models.ManyToManyField(related_name='emission_evaluators', to='database.producttransportemission')),
                ('resource_burnt_emissions', models.ManyToManyField(related_name='emission_evaluators', to='database.resourceburntemission')),
                ('resource_transport_emissions', models.ManyToManyField(related_name='emission_evaluators', to='database.resourcetransportemission')),
                ('waste_emissions', models.ManyToManyField(related_name='emission_evaluators', to='database.wasteemission')),
            ],
        ),
    ]
